# Configuration variables for the GitLab package

export GITLAB_ALL_VARIABLE_NAMES='$GITLAB_USER:$GITLAB_USER_ID:$GITLAB_USER_GID:$GITLAB_USER_HOME:$GITLAB_ROOT:$GITLAB_EMAIL_FROM:$GITLAB_FQDN:$GITLAB_RELATIVE_ROOT:$NGINX_PORT:$POSTGRESQL_PORT:$REDIS_PORT:$UNICORN_PORT'

export GITLAB_USER=git
export GITLAB_USER_UID=1028
export GITLAB_USER_GID=100
export GITLAB_USER_HOME=/var/services/homes/git

export GITLAB_ROOT=${GITLAB_USER_HOME}/gitlab
export GITLAB_EMAIL_FROM=example@example.com
export GITLAB_FQDN=localhost
export GITLAB_RELATIVE_ROOT=/gitlab

export NGINX_PORT=10080

export POSTGRESQL_PORT=15432
export REDIS_PORT=16379
export UNICORN_PORT=18080

